backend:
  name: git-gateway
  repo: 5SensesOfScience/5sosc-website
  branch: main
media_folder: "src/content/assets"
public_folder: "src/content/assets"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content"
    create: true
    slug: "{{slug}}"
    path: "{{locale}}/posts/{{slug}}"
    fields:
      - {
          label: "Locale",
          name: "locale",
          widget: "select",
          options: ["ca", "en", "es", "pl"],
        }
      - { label: "Key", name: "key", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Sense",
          name: "sense",
          widget: "select",
          options: ["Sight", "Hearing", "Taste", "Smell", "Touch"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
